{
  "openapi": "3.0.3",
  "info": {
    "title": "Port API",
    "version": "0.1"
  },
  "servers": [
    {
      "url": "https://api.getport.io/"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearer": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
    }
  },
  "paths": {
    "/v1/blueprints/{blueprint_identifier}/actions/{action_identifier}/permissions": {
      "get": {
        "tags": [
          "Actions"
        ],
        "security": [
          {
            "bearer": [
              "read:blueprints"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Actions"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/v1/blueprints/{blueprint_identifier}/permissions": {
      "get": {
        "tags": [
          "Blueprints"
        ],
        "security": [
          {
            "bearer": [
              "read:blueprints"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Blueprints"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/v1/auth/access_token": {
      "post": {
        "tags": [
          "Authentication / Authorization"
        ]
      }
    },
    "/v1/auth/permissions": {
      "get": {
        "tags": [
          "Authentication / Authorization"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/v1/blueprints": {
      "get": {
        "tags": [
          "Blueprints"
        ],
        "security": [
          {
            "bearer": [
              "read:blueprints"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Blueprints"
        ],
        "security": [
          {
            "bearer": [
              "create:blueprints"
            ]
          }
        ]
      }
    },
    "/v1/blueprints/{identifier}": {
      "get": {
        "tags": [
          "Blueprints"
        ],
        "security": [
          {
            "bearer": [
              "read:blueprints"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Blueprints"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "tags": [
          "Blueprints"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/v1/blueprints/{blueprint_identifier}/actions": {
      "post": {
        "tags": [
          "Actions"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "tags": [
          "Actions"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "get": {
        "tags": [
          "Actions"
        ],
        "security": [
          {
            "bearer": [
              "read:actions"
            ]
          }
        ]
      }
    },
    "/v1/blueprints/{blueprint_identifier}/actions/{action_identifier}": {
      "put": {
        "tags": [
          "Actions"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "get": {
        "tags": [
          "Actions"
        ],
        "security": [
          {
            "bearer": [
              "read:actions"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Actions"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/v1/actions": {
      "get": {
        "tags": [
          "Actions"
        ],
        "security": [
          {
            "bearer": [
              "read:actions"
            ]
          }
        ]
      }
    },
    "/v1/blueprints/{blueprint_identifier}/entities/{entity_identifier}/actions/{action_identifier}/runs": {
      "post": {
        "tags": [
          "Action Runs"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/v1/blueprints/{blueprint_identifier}/actions/{action_identifier}/runs": {
      "post": {
        "tags": [
          "Action Runs"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/v1/actions/runs/{run_id}": {
      "patch": {
        "tags": [
          "Action Runs"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "get": {
        "tags": [
          "Action Runs"
        ],
        "security": [
          {
            "bearer": [
              "read:runs"
            ]
          }
        ]
      }
    },
    "/v1/actions/runs": {
      "get": {
        "tags": [
          "Action Runs"
        ],
        "security": [
          {
            "bearer": [
              "read:runs"
            ]
          }
        ]
      }
    },
    "/v1/blueprints/{blueprint_identifier}/entities": {
      "post": {
        "tags": [
          "Entities"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/v1/blueprints/{blueprint_identifier}/entities/{entity_identifier}": {
      "patch": {
        "tags": [
          "Entities"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "tags": [
          "Entities"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "get": {
        "tags": [
          "Entities"
        ],
        "security": [
          {
            "bearer": [
              "read:entities"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Entities"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/v1/entities/search": {
      "post": {
        "tags": [
          "Entities"
        ],
        "security": [
          {
            "bearer": [
              "read:entities"
            ]
          }
        ]
      }
    },
    "/v1/pages": {
      "get": {
        "tags": [
          "Pages"
        ],
        "security": [
          {
            "bearer": [
              "read:pages"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Pages"
        ],
        "security": [
          {
            "bearer": [
              "create:pages"
            ]
          }
        ]
      }
    },
    "/v1/pages/{identifier}": {
      "get": {
        "tags": [
          "Pages"
        ],
        "security": [
          {
            "bearer": [
              "read:pages"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Pages"
        ],
        "security": [
          {
            "bearer": [
              "delete:pages"
            ]
          }
        ]
      }
    },
    "/v1/organization": {
      "get": {
        "tags": [
          "Organization"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "tags": [
          "Organization"
        ],
        "security": [
          {
            "bearer": [
              "update:organization"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Organization"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/v1/organization/document": {
      "post": {
        "tags": [
          "Organization"
        ]
      }
    },
    "/v1/integration/github": {
      "post": {
        "tags": [
          "Integrations"
        ],
        "security": [
          {
            "bearer": [
              "create:integrations"
            ]
          }
        ]
      }
    },
    "/v1/integration/github/{identifier}": {
      "delete": {
        "tags": [
          "Integrations"
        ],
        "security": [
          {
            "bearer": [
              "delete:integrations"
            ]
          }
        ]
      }
    },
    "/v1/audit-log": {
      "get": {
        "tags": [
          "Audit"
        ],
        "security": [
          {
            "bearer": [
              "read:audit-log"
            ]
          }
        ]
      }
    },
    "/v1/teams": {
      "get": {
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "bearer": [
              "read:teams"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "bearer": [
              "create:teams"
            ]
          }
        ]
      }
    },
    "/v1/teams/{name}": {
      "patch": {
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "bearer": [
              "update:teams"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "bearer": [
              "delete:teams"
            ]
          }
        ]
      }
    },
    "/v1/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearer": [
              "read:users"
            ]
          }
        ]
      }
    },
    "/v1/users/invite": {
      "post": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearer": [
              "create:users"
            ]
          }
        ]
      }
    },
    "/v1/users/{user_email}": {
      "get": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearer": [
              "read:users"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearer": [
              "update:users"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearer": [
              "delete:users"
            ]
          }
        ]
      }
    },
    "/v1/apps": {
      "get": {
        "tags": [
          "Apps"
        ],
        "security": [
          {
            "bearer": [
              "read:apps"
            ]
          }
        ]
      }
    },
    "/v1/roles": {
      "get": {
        "tags": [
          "Roles"
        ],
        "security": [
          {
            "bearer": [
              "read:roles"
            ]
          }
        ]
      }
    }
  }
}
